Provide an up-to-date feature-rich example serverless.yml config
brefphp/laravel-bridge pull request #103
Opened 2023-03-17 17:12 UTC by aran112000

Example serverless.yml config for the updated Laravel Bridge for Bref 2.

Default config for Octane support (simply swap the `web` functions over to use)

This uses Lift constructs to:
 - Create a default SQS queue and link to Laravel queues seamlessly
 - Create a Cloudfront website front-end and S3 bucket for serving static assets from within your domain

2023-03-17 17:51 UTC, tillkruss requested changes
The stub is being used as the default. Please add it yours to the examples directory.

2023-03-17 17:51 UTC, georgeboot commented
Seems to conflict with #100

Perhaps it's best to provide a simple default (like in #100) and document (or even, provide examples) of more advanced setups like the one in this PR?

Thoughts?

2023-03-17 18:22 UTC, aran112000 commented
No worries, I'll review this weekend and move it over to the examples

2023-03-17 18:42 UTC, tillkruss commented
> Perhaps it's best to provide a simple default (like in #100) and document (or even, provide examples) of more advanced setups like the one in this PR?

I was thinking we have a dozen example files (or folders) in `examples`.

2023-03-20 13:17 UTC, mnapoli reviewed
+1 on moving this to an example. In the meantime, I reviewed the current diff in case that helps! (added comments inline)

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +  stage: dev
I would remove this line because this is the default, and overriding it makes more sense via a CLI flag. (i.e. this option is for the "default stage", and it wouldn't make sense to change it for most users, unlike e.g. the region)

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +      stage: ${opt:stage, self:provider.stage}
I like the idea but I don't think this works: https://github.com/serverless/serverless/issues/10683

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +  #  timeout: 30 # in seconds
Should be 28 like the other one above

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +          rate: rate(5 minutes)
Unfortunately we'll need to switch to `1 minute` per https://github.com/brefphp/laravel-bridge/pull/100#discussion_r1138961907

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +      timeout: 59
Timeout could be longer than that I think? (I.e. no particular reason for 59?)

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +      '/build/assets/*.js': public/build/assets
Could this be simplified to:

```suggestion
      '/build/assets/*': public/build/assets
```

?

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +  scriptable:
Does this require a plugin to be installed and enabled (in `plugins:` below)?

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +    laravel_debug: true
I wouldn't enable debug by default (https://github.com/brefphp/laravel-bridge/pull/100#discussion_r1139049805)

I think this could be a very security issue because it would expose AWS credentials and other credentials (e.g. API tokens, DB passwords) by default and all the time publicly on the internet? Or am I missing something?

2023-03-20 13:17 UTC, mnapoli commented on stubs/serverless.yml
> +    amazon_ssl_arn: arn:aws:acm:us-east-1:xxxxxxxxx:certificate/xxxx-xxxx-xxxx # TODO: Issue and verify SSL - Must be created within *us-east-1* here: https://us-east-1.console.aws.amazon.com/acm/hom
I would link to https://bref.sh/docs/websites.html#setting-up-a-domain-name because it contains a whole tutorial for setting up the certificate

2023-03-20 19:54 UTC, aran112000 commented on stubs/serverless.yml
> +  logRetentionInDays: ${param:log_retention_days}
Good suggestion, just setting a default retention period across all envs will be fine for most users

2023-03-20 19:59 UTC, aran112000 commented on stubs/serverless.yml
> +      stage: ${opt:stage, self:provider.stage}
I took this from an existing config we use that works fine?

2023-03-20 20:01 UTC, aran112000 commented on stubs/serverless.yml
> +      timeout: 59
Updated to 720 to match the artisan handler

2023-03-20 20:05 UTC, aran112000 commented on stubs/serverless.yml
> +    laravel_debug: true
Very good point, we run all our staging environments where they can only be seen through a VPN so the debug views can be helpful in staging, but for most users, that's probably a terrible idea - reverting

2023-03-20 20:17 UTC, closed without merging

2023-03-20 22:50 UTC, tillkruss commented
I'm ooo this week. @georgeboot @mnapoli

2023-03-21 10:20 UTC, georgeboot commented on examples/ququed/serverless.yml
Type on filename

2023-03-21 10:20 UTC, georgeboot commented on examples/ququed/serverless.yml
> +#  - serverless plugin install -n serverless-scriptable-plugin
Since the example is in its own directory, maybe we should create a separate markdown file as well that explains all the steps? Much easier to read imho

2023-03-21 10:20 UTC, georgeboot commented on examples/ququed/serverless.yml
> +    APP_ENV: ${param:laravel_env}
Why use a param and not just `${sls:stage}`?