Option to not update configs with AWS tokens
brefphp/laravel-bridge pull request #123
Opened 2023-06-20 11:05 UTC by mchristie

Although it's recommended to use AWS roles that's not always possible.

If the application is setting AWS keys and secrets with credentials which do not need an AWS token, adding the token in from the function role will cause the credentials to become invalid.

This PR adds a config option which disables updating the AWS configs with AWS_SESSION_TOKEN

2023-06-20 11:25 UTC, tillkruss requested changes

2023-06-20 11:25 UTC, tillkruss commented on config/bref.php
> +    'aws_session_tokens' => true,
Let's call this `use_session_token`.

2023-06-20 11:25 UTC, tillkruss commented on src/BrefServiceProvider.php
> +
Remove extra whitespace.

2023-06-20 11:25 UTC, tillkruss commented on src/BrefServiceProvider.php
> +            $this->fixAWSCredentials();
Let's just inline the code, no need to extract it into a method.

2023-06-20 11:52 UTC, tillkruss commented on config/bref.php
> +    'use_session_tokens' => true,
@mnapoli: I'd say "session token", what do you reckon?

2023-06-20 12:52 UTC, mnapoli commented on config/bref.php
> +    'use_session_tokens' => true,
+1 for the singular version since it's one token

2023-06-20 12:52 UTC, mnapoli commented on config/bref.php
> +    | If you are not using AWS Roles you may need to disable this.
Uploading AWS credentials in Lambda is a very last resort option honestly, I'd love to know when it's not possible to use the Lambda credentials?

Anyway, I'd optimize for being super explicit that most users should not do this/use this, unless they definitely know why they are doing this. So I'd reword probably like this:

```suggestion
    | Bref fixes Laravel to use the AWS_SESSION_TOKEN environment variable
    | provided by AWS Lambda automatically (required for AWS credentials to work).
    | You should disable that only if you set your own AWS access keys manually
    | (which is not recommended in most cases).
```

2023-06-20 13:36 UTC, mchristie commented on config/bref.php
> +    | If you are not using AWS Roles you may need to disable this.
Totally agree it's a last resort. Our AWS setup has a lot of legacy and we have many clients with DKIM etc in SES in one region/account, but for various reasons we're also sending emails from another AWS account. We use roles for most things, but in this case we need to use different credentials for connecting to SES.

2023-06-20 14:56 UTC, mnapoli approved these changes

2023-07-02 00:45 UTC, deleugpn commented
My take on this is that the behavior of the adapter is to casually adjust Laravel's default installation for a quick drop-in replacement for Lambda. If you're deploying your project into Lambda it's an opportunity to replace secret keys with IAM Roles.
However, if you have reasons to stick with access key / secret key, all you'd have to do is change the name of the driver / connection you're using. E.g. if instead of using the `s3` disk on your filesystems config, you could just name it something else like `bucket` or `storage` or the business meaning behind the files that get stored there. Anything that is not the default laravel installation configuration wouldn't be touched by the Bridge and you'd be free to configure it however you feel like it.
It seems like a low effort on the user's part and one less configuration that Bref would have to maintain.

2023-07-02 06:53 UTC, georgeboot approved these changes

2023-07-02 14:26 UTC, mnapoli commented
Yeah, I'd tend to agree with @deleugpn as this is a niche use case. I'm not against merging this, but I'm not especially pushing for it. I'll let you guys decide.

2024-07-31 09:24 UTC, closed without merging