fix: resolve Laravel home using __DIR__
brefphp/laravel-bridge pull request #130
Opened 2023-09-22 16:02 UTC by jaulz

When using a mono repository, the Laravel folder is not the root folder. Hence, we cannot simply take the Lambda Root and expect Laravel files to be present. Instead, this PR uses the current directory of the script and just finds the Laravel files relatively via going up the directory tree.

2023-09-22 16:46 UTC, tillkruss requested changes

2023-09-22 16:46 UTC, tillkruss commented on src/bref-init.php
> +    $laravelHome = __DIR__ . '/../../../../';
This is way to ambitious. Use a constant or add a custom ENV variable instead.

2023-09-22 17:36 UTC, deleugpn commented on src/bref-init.php
> +    $laravelHome = __DIR__ . '/../../../../';
I kinda prefer this over more configuration options tbh...

2023-09-26 13:08 UTC, tillkruss requested changes

2023-09-26 13:08 UTC, tillkruss commented on src/bref-init.php
> +    $laravelHome = $_ENV['LARAVEL_HOME'] ?? __DIR__ . '/../../../../';
Please default to `LAMBA_ROOT_TASK`.

2023-09-26 13:18 UTC, jaulz commented on src/bref-init.php
> +    $laravelHome = $_ENV['LARAVEL_HOME'] ?? __DIR__ . '/../../../../';
done 😊

2023-09-26 13:26 UTC, deleugpn commented
I just opened https://github.com/brefphp/laravel-bridge/pull/131 as an alternative to this and explained why I preferred the previous approach.

2023-09-26 13:29 UTC, deleugpn requested changes
I'm tagging this with request changes so that we can better discuss the alternative approach on #131 before merging. If we still opt for this option, I'd like to get the HandlerResolver also implemented to solve loading namespaced Handlers with custom vendor.

2023-09-26 14:20 UTC, jaulz commented on src/bref-init.php
> +    $laravelHome = $_ENV['LAMBA_ROOT_TASK'] ?? __DIR__ . '/../../../../';
Ah, I thought it's just the preferred name of the variable 😉  I renamed it temporarily and wait for #131 instead then.

2024-03-03 19:09 UTC, deleugpn commented
#131 has been merged and should address this, so I'm going to close this one.

If the author, or anybody else, feels differently, please feel free to open an issue or another PR for us to discuss it further!

2024-03-03 19:09 UTC, closed without merging