Allow to run Laravel under custom vendor location
brefphp/laravel-bridge pull request #131
Opened 2023-09-26 13:25 UTC by deleugpn

This is basically the same as https://github.com/brefphp/laravel-bridge/pull/130.

There are 2 places right now that breaks when installing Laravel under a monorepo setup without the standard Laravel folder structure - the bref-init.php makes reference to `php artisan` in the root of the folder and the HandlerResolver container assumes `bootstrap/app.php` inside `/var/task`.

The linked PR attempts (at request of @tillkruss) to implement an environment variable. That approach has a few downsides:

- Dynamic configuration options for things that can be resolved statically.
- Use of `LARAVEL_` environment prefix outside of Laravel ownership
- Forces Bref users to configure Bref to locate something that Bref can locate automatically.

We could still opt to use an environment variable if that's the preferred approach among the maintainers, but such variable should not be under the `LARAVEL_` namespace unless Laravel themselves provide the value by default.

2023-09-26 13:33 UTC, tillkruss requested changes
Don't change defaults. Make it configurable.

2023-09-26 13:39 UTC, deleugpn commented
hey @tillkruss can you expand a little on why you want to create configurable runtime dynamic variables with a worse user-experience for users instead of implementing a better default value?

2023-09-26 16:16 UTC, tillkruss commented on src/HandlerResolver.php
> +        $bootstrapFile = __DIR__ . '/../../../../bootstrap/app.php';
Can we use `realpath()` on both strings?

2023-09-26 16:20 UTC, tillkruss commented
> hey @tillkruss can you expand a little on why you want to create configurable runtime dynamic variables with a worse user-experience for users instead of implementing a better default value?

@deleugpn: I may simply not understand the use-case and this change looks like a potential breaking-change to me.

Not changing the default behavior and allowing the 1 user who needs this to specify a custom path using an ENV variable seems like the lowest risk to me.

2023-09-26 17:30 UTC, deleugpn commented
> @deleugpn: I may simply not understand the use-case and this change looks like a potential breaking-change to me.

What can I explain that would help you understand the use-case and show that this is not a breaking change?

> Not changing the default behavior and allowing the 1 user who needs this to specify a custom path using an ENV variable seems like the lowest risk to me.

I need this for myself, so now we're 2 users. The creation of configuration values increases the internal compleixty of the package as it leads to different execution path depending on how the end user interacts with it. The end user needing to override the default value with a configuration is also added burden. It's lose-lose situation for both users and maintainers.

2023-09-26 18:49 UTC, tillkruss approved these changes

2023-09-26 18:49 UTC, tillkruss commented on src/bref-init.php
> +    $laravelHome = realpath(__DIR__ . '/../../../../');
Should we use the same logic as in `HandlerResolver`?

2023-09-27 07:00 UTC, mnapoli commented on src/HandlerResolver.php
> +        if (file_exists(__DIR__ . '/../../../../bootstrap/app.php')) {
How did you come up with that path? Is it relative to the `vendor` directory? Is the number of `..` always the same?

(I'd like to push the answer to that question into the code as a comment so that we can understand it when looking back to it later)

2023-09-27 07:01 UTC, mnapoli commented on src/HandlerResolver.php
> +        if (file_exists(__DIR__ . '/../../../../bootstrap/app.php')) {
Oh also: why not use that path always? Are there cases where it wouldn't work?

2023-09-27 11:42 UTC, deleugpn commented on src/HandlerResolver.php
> +        if (file_exists(__DIR__ . '/../../../../bootstrap/app.php')) {
> How did you come up with that path? Is it relative to the vendor directory? Is the number of .. always the same?

It's `vendor/packageOwner/PackageName/src`. Since we have `src` inside this project and composer packages are formed by 2-folder, that gives us 3 levels. The 4th level is the vendor itself.

> Oh also: why not use that path always? Are there cases where it wouldn't work?

@tillkruss was not happy with it fearing a potential BC break.

2023-09-27 15:20 UTC, tillkruss commented on src/HandlerResolver.php
> +        if (file_exists(__DIR__ . '/../../../../bootstrap/app.php')) {
My suggestion was `getcwd()` works for ~99% of installs, let's add a `LARAVEL_HOME` environment variable if people need to customize it.

2023-09-29 09:24 UTC, mnapoli commented on src/HandlerResolver.php
> +        if (file_exists(__DIR__ . '/../../../../bootstrap/app.php')) {
Oh OK, that makes a lot of sense!

> My suggestion was getcwd() works for ~99% of installs

Right, but this new solution should work for 100% of installs? I don't see a scenario where this wouldn't work now, well… except if someone doesn't use Composer, but then that's not something we want to support.

I'd go with relative path everywhere then (like many packages already do, e.g. in bref https://github.com/brefphp/bref/blob/master/bref#L12). No need for yet another env variable?

2023-10-06 12:08 UTC, deleugpn commented
hey sorry folks, I've been using this branch in production for the last week and I haven't had time to clean this up to make it ready for merge. I haven't forgotten about it, I will get to it as soon as I finish my ongoing project.

2023-11-06 17:38 UTC, tillkruss approved these changes

2023-11-09 10:12 UTC, deleugpn commented
hey @mnapoli and @tillkruss, we have tested this out on AWS Lambda and it seems to be working as expected. The only last concern I have is in regards to `bref-init.php` defining the function `resolveBootstrapLocation`. Since this is a function definition without namespace, it could potentially clash with userland code defining a function with the same name.

Any suggestions on this?

2023-11-09 10:33 UTC, mnapoli commented on src/HandlerResolver.php
> +    private function resolveBootstrapLocation(): string
This function seems to duplicate the other `resolveBootstrapLocation()` function, but with a slightly different implementation (but same name), any reason for that?

Can we merge both functions into one?

2023-11-09 10:34 UTC, mnapoli commented
That's great, I added one comment inline.

> Since this is a function definition without namespace, it could potentially clash with userland code defining a function with the same name.

How about namespacing the function? That would solve the problem without any weird thing?

2023-11-13 14:41 UTC, deleugpn commented on src/bref-init.php
> +    return realpath(__DIR__ . '/../../../../');
hey @alustau this is breaking the invocation of `php artisan config:cache` because `realpath()` returns the folder without the last `/`. We need to concatenate `/` at the end of the string

2023-11-13 16:18 UTC, alustau commented on src/bref-init.php
> +    return realpath(__DIR__ . '/../../../../');
Fixed!

2023-11-23 21:22 UTC, mnapoli commented on src/bref-init.php
> +    return realpath(__DIR__ . '/../../../../');
This inline comment is not marked as "obsolete", is this resolved? I didn't see any new commits related to this, not sure what to do.

2023-11-24 11:22 UTC, deleugpn commented on src/bref-init.php
> +    return realpath(__DIR__ . '/../../../../');
I had forgotten to merge the PR that was addressing this 😅

2023-11-24 11:22 UTC, deleugpn commented on src/HandlerResolver.php
> +    private function resolveBootstrapLocation(): string
I just addressed this

2023-11-24 11:29 UTC, deleugpn commented
hey @tillkruss and @mnapoli really sorry for how long this has dragged on. I just did a last round of refactoring to get all changes to a central place and address it in a more consistent manner.

The goal is for the `LaravelPathFinder::root()` method to return the root folder of Laravel, always, without a leading slash. The original implementation was kept for BC purposes.

Whenever `LaravelPathFinder::root()` is used, we can go ahead and concatenate it with a slash `/` plus whatever path we're looking for.

I'm deploying this change in my project right now to test it out inside AWS Lambda.

2023-11-24 11:44 UTC, deleugpn commented
I have not tested this in production yet, but I did a few tests on a staging environment with a real AWS Lambda. Everything is working as expected.

2023-12-07 00:27 UTC, KentarouTakeda reviewed
It seems that there is a conflict due to my Pull Request https://github.com/brefphp/laravel-bridge/pull/143 that was merged yesterday.

I have confirmed that the following modification works fine.

2023-12-07 00:27 UTC, KentarouTakeda commented on src/bref-init.php
> +        fwrite(STDERR, "Running 'php $laravelRoot/artisan config:cache' to cache the Laravel configuration\n");
```suggestion
        $outputDestination = '> /dev/null';
        if (!getenv('BREF_LARAVEL_OMIT_INITLOG')) {
            fwrite(STDERR, "Running 'php $laravelRoot/artisan config:cache' to cache the Laravel configuration\n");
            // 1>&2 redirects the output to STDERR to avoid messing up HTTP responses with FPM
            $outputDestination = '1>&2';
        }
```

2023-12-07 00:27 UTC, KentarouTakeda commented on src/bref-init.php
> +        passthru("php $laravelRoot/artisan config:cache 1>&2");
```suggestion
        passthru("php artisan config:cache {$outputDestination}");
```

2024-02-19 13:26 UTC, deleugpn commented
Hey @tillkruss and @mnapoli 

I just noticed I've been running this branch on production since December. Looks like I completely forgot to follow up on this.

I just fixed the conflicts that @KentarouTakeda mentioned, but if we have no other objections, this is good to go.

2024-03-03 13:32 UTC, mnapoli approved these changes

2024-03-03 13:32 UTC, merged