Bump laravel Octane version for Laravel 10 compatibility
brefphp/laravel-bridge pull request #133
Opened 2023-10-19 00:59 UTC by natanparmigianoreis

Currrently the package is marked as compatible with octane 1.2 explicitly, which makes any Laravel 10.x (which is only compatible with octane 2.x) instalation fall back to bref/laravel-bridge:^1.2 , since that is the last version that does not include the octane requirement in its dependencies.

This pull request bumps the required octane version to "^2.1" making it compatible with Laravel 10.x

Resolves issue #132

2023-10-20 00:39 UTC, tillkruss requested changes

2023-10-20 00:39 UTC, tillkruss commented on composer.json
> +        "laravel/octane": "^2.1",
How about `^1.2 || ^2.0`?

2023-11-07 06:16 UTC, gazzoy commented
+1 for this

2024-07-30 12:43 UTC, mnapoli commented
This was implemented in another PR.

2024-07-30 12:43 UTC, closed without merging