Set correct queue name from sqs job event
brefphp/laravel-bridge pull request #139
Opened 2023-11-11 23:28 UTC by vmiguellima

2023-11-13 18:39 UTC, tillkruss requested changes

2023-11-13 18:39 UTC, tillkruss commented on src/Queue/QueueHandler.php
> +            $sqsRecord->getQueueName() ?? $this->queueName,
This would require a new helper method, if the queue-name is stored in `$record`.

2023-11-13 18:40 UTC, tillkruss approved these changes

2023-11-14 14:05 UTC, mnapoli commented on src/Queue/QueueHandler.php
> +            $sqsRecord->getQueueName() ?? $this->queueName,
Oh this is good, thank you!

The new method will either exist (latest Bref version) or not, so I don't think the `??` needs to exist:

```suggestion
            $sqsRecord->getQueueName(),
```

Which also means you'll need to bump the required Bref version in `composer.json` to https://github.com/brefphp/bref/releases/tag/2.1.8

2023-11-14 20:34 UTC, vmiguellima commented on src/Queue/QueueHandler.php
> +            $sqsRecord->getQueueName() ?? $this->queueName,
Done.

2023-11-20 09:28 UTC, mnapoli approved these changes
Thanks for the changes, that looks awesome

2023-11-21 20:24 UTC, vmiguellima commented
@tillkruss @mnapoli Could this be merge? it would unlock me 😅

2023-11-23 21:20 UTC, merged