Setting whether to output the initialization log
brefphp/laravel-bridge pull request #143
Opened 2023-11-26 09:54 UTC by KentarouTakeda

Hi!

In this pull request, I propose a configurable option to selectively enable logging for the Laravel application initialization process orchestrated by Bref.

Added `log_init` option to the config file published with `php artisan vendor:publish --tag=bref-config`.

### Motivation

The intention is to streamline the log output to CloudWatch by allowing selective logging, enhancing the readability and utility of the logs.

Currently, logs such as the following are output.

```
Creating storage directories: /tmp/storage/bootstrap/cache, /tmp/storage/framework/cache, /tmp/storage/framework/views, /tmp/storage/psysh
Running 'php artisan config:cache' to cache the Laravel configuration
INFO  Configuration cached successfully.  
```

These logs are useful for understanding how Bref is working within the Lambda runtime and whether the configuration of the Laravel application we have deployed is as intended.

However, this verbosity becomes superfluous when multiple cold starts occur in rapid succession, as the same messages are replicated each time.
*(For example, when `Bref\LaravelBridge\Queue\QueueHandler` handles a large number of "Push Notifications" sent simultaneously)*

This option aims to provide flexibility in managing log verbosity based on the developers' needs during different stages of deployment and operation.

Thank you.

2023-11-26 09:56 UTC, KentarouTakeda commented
This fix may solve some of the issues in #134.

The issue also mentions changes to the log output destination and format. Although these points are not supported by this Pull Request, it will prevent log output in a format other than Json from interfering with other programs.

/cc @micheleorselli

2023-11-26 16:34 UTC, georgeboot commented on src/bref-init.php
> +    $shouldLogInit = (bool)($config['log_init'] ?? true);
Maybe this should just be an env variable advanced users can set?

2023-11-27 01:39 UTC, KentarouTakeda commented on src/bref-init.php
> +    $shouldLogInit = (bool)($config['log_init'] ?? true);
@georgeboot 
Corresponded with https://github.com/brefphp/laravel-bridge/pull/143/commits/bcc55118525bd2a876a6446c0f923985281d21e9 .You can also control it with the environment variable `BREF_LARAVEL_BRIDGE_LOG_INIT`.

2023-11-27 01:40 UTC, KentarouTakeda commented on src/bref-init.php
> +    $shouldLogInit = (bool)($config['log_init'] ?? true);
@mnapoli 
Please let me know if the naming convention for environment variables is incorrect. If so, I will fix it immediately.

Although it is outside the scope of this Pull Request, I think it would be better to do the same for `request_context` in the same location to unify it. Should I add it to this pull request? Or (if you can merge this) I can send you another pull request.

2023-11-27 07:39 UTC, georgeboot commented on src/bref-init.php
> +    $shouldLogInit = (bool)($config['log_init'] ?? true);
Thanks for your prompt changes!

What I meant though, is to say if it's even needed to make it an option in config/bref.php. We now have to manually read and merge config (because Laravel hasn't bootstrapped yet etc). Since this is probably a pro-feature, my suggestion would be to not touch the config file at all and just expose the option as an env only.

@mnapoli what do you think?

2023-11-27 07:50 UTC, KentarouTakeda commented on src/bref-init.php
> +    $shouldLogInit = (bool)($config['log_init'] ?? true);
Actually, I was considering that before sending the pull request. This time, I thought it would be better to set it in the config file for the following reasons.

* This method is familiar to Laravel users and is consistent with other methods.
* There may be a possibility to use this option even after initializing the Laravel application due to future feature additions. For example, internal use of `BrefServiceProvider`.

2023-11-27 17:06 UTC, tillkruss commented on src/bref-init.php
> +    $shouldLogInit = (bool)($config['log_init'] ?? true);
I agree with @georgeboot here. I like the ability to disable logging, but the code above is unnecessary. A `getenv()` check seems reasonable.

2023-11-28 04:02 UTC, KentarouTakeda commented on src/bref-init.php
> +    $shouldLogInit = (bool)($config['log_init'] ?? true);
@georgeboot @tillkruss 
fixed in https://github.com/brefphp/laravel-bridge/pull/143/commits/56e2de694af2af47e83a9ce3e3ef2b810e6822df

2023-11-28 16:20 UTC, tillkruss requested changes

2023-11-28 16:20 UTC, tillkruss commented on src/StorageDirectories.php
> +    public static function create(bool $shouldLog)
Just check `BREF_LARAVEL_BRIDGE_LOG_INIT` in here, no need to pass it in.

2023-11-28 16:20 UTC, tillkruss commented on src/bref-init.php
> +        getenv('BREF_LARAVEL_BRIDGE_LOG_INIT') === false ? true
@georgeboot I tend to only check for truthy values, never strict when using ENV variables, what do you think?

2023-11-28 21:16 UTC, georgeboot commented on src/bref-init.php
> +        getenv('BREF_LARAVEL_BRIDGE_LOG_INIT') === false ? true
Yeah agreed

2023-11-28 23:48 UTC, KentarouTakeda commented on src/StorageDirectories.php
> +    public static function create(bool $shouldLog)
Fixed in https://github.com/brefphp/laravel-bridge/pull/143/commits/84e5d419714c0b7f4b767df79da98ed0dfcff6fc

Please see also this next comment.

2023-11-28 23:55 UTC, KentarouTakeda commented on src/bref-init.php
> +        getenv('BREF_LARAVEL_BRIDGE_LOG_INIT') === false ? true
Fixed in https://github.com/brefphp/laravel-bridge/pull/143/commits/8614317c8a134077967ae46b6ba75d4ddec50fd0

@tillkruss @georgeboot 

I agree with that, but there are some caveats.

It is not possible to distinguish between cases where `'0'` is explicitly entered using this Pull Request feature and cases where the environment variable is not set in the previous settings and evaluates to `false` .

As a result, init logs will no longer be output even for users who do nothing.
(IMO: I think it's no problem since it's not considered an important log)

If there is no problem with that, I think this is better!

2023-11-29 17:53 UTC, tillkruss commented on src/StorageDirectories.php
> +        if (count($directories) && defined('STDERR') && getenv('BREF_LARAVEL_BRIDGE_LOG_INIT')) {
@mnapoli: I don't like how verbose `BREF_LARAVEL_BRIDGE_LOG_INIT`, any thoughts?

2023-11-29 23:23 UTC, KentarouTakeda commented on src/StorageDirectories.php
> +        if (count($directories) && defined('STDERR') && getenv('BREF_LARAVEL_BRIDGE_LOG_INIT')) {
@tillkruss 
Fixed in https://github.com/brefphp/laravel-bridge/pull/143/commits/d9fb90afcac68c0ce980dad3bb3a2dc4fb3fcdc5

I found an environment variable called `BREF_LARAVEL_CACHE_CONFIG`. By unifying it with that, it became shorter. If you don't like this either, please tell me what to do.

You might be able to use your time more effectively if you summarize your reviews to a certain extent instead of just one review a day!

2023-12-05 11:26 UTC, KentarouTakeda commented
@tillkruss @georgeboot 
I think I have corrected all the points you have pointed out. Did you have any other problems?

2023-12-05 14:29 UTC, georgeboot commented
I like the feature as is, but personally would flip the logic and make logging opt-out using environment variables. It's now _technically_ a breaking change and only few users will care about it.

2023-12-05 16:57 UTC, tillkruss commented
> I like the feature as is, but personally would flip the logic and make logging opt-out using environment variables. It's now _technically_ a breaking change and only few users will care about it.

Agreed.

2023-12-06 00:47 UTC, KentarouTakeda commented
Fixed in https://github.com/brefphp/laravel-bridge/pull/143/commits/cf92542c151678ecffdeb706461a6b60d0abffc4

For details such as the name, I have enabled *"Allow edits and access to secrets by maintainers"* setting in the Pull Request, so feel free to modify it in any way you like.

2023-12-06 09:47 UTC, georgeboot approved these changes

2023-12-06 10:02 UTC, mnapoli approved these changes

2023-12-06 16:57 UTC, tillkruss approved these changes

2023-12-06 18:09 UTC, merged