Run tests on PHP 8.1
brefphp/laravel-bridge pull request #64
Opened 2022-01-31 18:41 UTC by hmazter

2022-01-31 19:15 UTC, hmazter commented
Not sure if it's possible to have a Test App that is installable on both PHP 7.3 and PHP 8.1 with appropriate dependencies.

2022-02-01 15:43 UTC, mnapoli commented
Would it help if we dropped support for Laravel 6?

2022-02-02 07:58 UTC, hmazter commented
I have updated the test app to a version (Laravel 8) that should be installable on everything from PHP 7.3 to PHP 8.1.
But it is actually one version of Laravel that is tests, I don't know if that is an issue?

2022-02-10 08:44 UTC, kris914g commented
What needs to be done to merge this PR? Would like to have Laravel 9 support 😄

2022-02-10 08:52 UTC, hmazter commented
The thing that fails now in CI is PHPCS can not run because of this:

```
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.12.
```

I'm not sure if I upgrade some dependencies that do not need an upgrade, or if phpcs needs to be updated.

2022-02-10 10:00 UTC, kris914g commented
Alright, I believe the issue is regarding the composer.json since Laravel 9 has dropped support for all PHP versions below PHP 8. So to fix the issue, we must update the PHP version in composer.json. Laravel version 6 also supports PHP 8 so Laravel version 6 can still be supported, I suppose with the following change: `"php": "^8.0",`

2022-02-10 10:02 UTC, kris914g requested changes
Alright, I believe the issue is regarding the composer.json since Laravel 9 has dropped support for all PHP versions below PHP 8. So to fix the issue, we must update the PHP version in composer.json. Laravel version 6 also supports PHP 8 so Laravel version 6 can still be supported, I suppose with the following change: "php": "^8.0",

2022-02-10 10:02 UTC, kris914g commented on composer.json
>          "php": ">=7.3",
```suggestion
        "php": "^8.0",
```

2022-02-10 10:02 UTC, kris914g commented on .github/workflows/ci.yml
> +                  php-version: '7.3'
```suggestion
                  php-version: '8.0'
```

2022-02-10 10:12 UTC, hmazter commented on .github/workflows/ci.yml
> +                  php-version: '7.3'
I don't think this can be bumped, then the test for the old versions will fail.

It's this one that fails, `chekalsky/phpcs-action@v1` is built on PHP 7.4 I think.
https://github.com/brefphp/laravel-bridge/blob/36111f777e78759c2f20e9555dea2cd92e606916/.github/workflows/static.yml#L19-L32

2022-02-10 10:30 UTC, kris914g commented on .github/workflows/ci.yml
> +                  php-version: '7.3'
I see, just looked at the GA and it is based on [cytopia/phpcs:3](https://hub.docker.com/r/cytopia/phpcs) docker image, which only supports PHP version 7.4 and it haven't been upgraded for more than a year now, so to satisfy the test we must replace the GA with another CodeSniffer action which supports PHP 8

2022-02-10 10:51 UTC, mnapoli commented on .github/workflows/ci.yml
> +                  php-version: '7.3'
I'm 👍  with requiring PHP 8 if it helps here.

Also maybe this approach can be copied to get rid of this custom action: https://github.com/brefphp/bref/blob/master/.github/workflows/ci.yml#L75-L96 ?

2022-02-10 11:02 UTC, kris914g commented on .github/workflows/ci.yml
> +                  php-version: '7.3'
That would work, we just need to add the Code_Sniffer package into composer.json and maybe it could be a good idea to just add a matrix to use several PHP versions. I can make a PR with an update phpcs action later today

2022-02-10 11:34 UTC, hmazter commented on .github/workflows/ci.yml
> +                  php-version: '7.3'
Updated the phpcs workflow according to the link @mnapoli sent

2022-02-14 11:38 UTC, kris914g approved these changes

2022-02-16 08:22 UTC, kris914g commented
Can we get this merged soon?

2022-02-24 09:02 UTC, kris914g commented
> Can we get this merged soon?

@mnapoli is there something we are waiting for before we can merge?

2022-02-25 00:55 UTC, omarkdev commented
It's possible to merge this one soon?

2022-02-26 13:18 UTC, mnapoli commented
@omarkdev please calm down, this is becoming rude.

2022-02-26 13:18 UTC, merged

2022-02-26 13:18 UTC, mnapoli commented
Thanks @hmazter!